### ISSUE TITLE
koin annotations

### ISSUE THREAD

**Issue by YoussefHachicha** [DoTheMonkeyBusiness/CopartAdvancedAuction#30]
you made a blog about koin annotation in KMP but while inspecting your project I didn't see any usage of it

**Comment by DoTheMonkeyBusiness** [comment]
Hi @YoussefHachicha!

Yeah, because of the issues that I described in [my article](https://medium.com/proandroiddev/nine-circles-of-hell-to-migrate-a-kotlin-multiplatform-project-to-the-koin-annotations-c956f3155a59) I couldn't migrate to koin-annotations.
